plugins {
    id 'com.android.application'
    id 'dev.rikka.tools.refine'
}

android {
    namespace 'roro.stellar.shell'
    defaultConfig {
        applicationId 'roro.stellar.shell'
        versionCode rootProject.ext.versionCode
        versionName rootProject.ext.versionName
    }
    buildTypes {
        debug {
            multiDexEnabled false
        }
        release {
            minifyEnabled true
            proguardFiles 'proguard-rules.pro'
        }
    }
    dependenciesInfo {
        includeInApk false
    }
    lint {
        checkReleaseBuilds false
    }
    buildFeatures {
        buildConfig = true
    }
}

android.applicationVariants.configureEach { variant ->
    variant.outputs.configureEach {
        def dexPath = "${rootProject.rootDir.path}/manager/src/main/assets"
        variant.assembleProvider.get().doLast {
            copy {
                def dexFiles = zipTree(file(outputFile)).matching { include 'classes*.dex' }.files
                from dexFiles
                into dexPath
                rename { String fileName -> "stsh_stellar.dex" }
            }
        }
    }
}

dependencies {
    implementation libs.hidden.compat
    compileOnly libs.hidden.stub
}
